import { useCallback, useEffect, useState, type FormEvent } from "react";
import { createAccessUser, getAccessUsers, replaceUserCapabilities, setAccessUserActive } from "../../../entities/service-desk-user/api/serviceDeskUserApi";
import type { ServiceDeskUser } from "../../../entities/service-desk-user/model/types";
import { useServiceDeskAccess } from "../../../app/providers/ServiceDeskAccessProvider";
import { Header } from "../../../widgets/header/ui/Header";
import { ServiceDeskAdminNav } from "../../../widgets/service-desk-admin-nav/ui/ServiceDeskAdminNav";
import { Button } from "../../../shared/ui/Button"; import { Card } from "../../../shared/ui/Card"; import { Input } from "../../../shared/ui/Input"; import { PageLayout } from "../../../shared/ui/PageLayout"; import { Select } from "../../../shared/ui/Select"; import { Table } from "../../../shared/ui/Table";

const capabilities=["service_desk.access","service_desk.create_request","service_desk.be_assignee","service_desk.approve","service_desk.assign","service_desk.change_priority","service_desk.view_all_tickets","service_desk.view_reports","service_desk.manage_catalog","service_desk.manage_templates","service_desk.manage_approval_workflows","service_desk.manage_routing","service_desk.manage_sla","service_desk.manage_access"];
const labels: Record<string,string>={"service_desk.access":"Основной доступ","service_desk.create_request":"Создание заявок","service_desk.be_assignee":"Работа исполнителем","service_desk.approve":"Согласование","service_desk.assign":"Назначение","service_desk.change_priority":"Изменение приоритета","service_desk.view_all_tickets":"Все заявки","service_desk.view_reports":"Отчёты","service_desk.manage_catalog":"Каталог","service_desk.manage_templates":"Шаблоны","service_desk.manage_approval_workflows":"Процессы согласования","service_desk.manage_routing":"Маршрутизация","service_desk.manage_sla":"SLA и календари","service_desk.manage_access":"Менеджеры и права"};
export function ServiceDeskAdminAccessPage(){
 const {user:actor,refresh}=useServiceDeskAccess(); const [users,setUsers]=useState<ServiceDeskUser[]>([]); const [q,setQ]=useState(""); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const p=new URLSearchParams({page_size:"100"});if(q)p.set("q",q);setUsers((await getAccessUsers(p)).items);setError(null);}catch(e){setError(e instanceof Error?e.message:"Ошибка доступа");}},[q]); useEffect(()=>{void load();},[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const d=new FormData(form);await createAccessUser({identity_user_id:d.get("identity"),email:d.get("email"),display_name:d.get("name"),department:d.get("department")||null,position:d.get("position")||null,access_type:d.get("type"),capabilities:d.get("type")==="manager"?["service_desk.access"]:[]});form.reset();await load();}
 async function toggle(user:ServiceDeskUser,capability:string){await replaceUserCapabilities(user.id,user.capabilities.includes(capability)?user.capabilities.filter(v=>v!==capability):[...user.capabilities,capability]);await load();if(user.id===actor?.id)await refresh();}
 async function active(user:ServiceDeskUser){if(!window.confirm(`${user.is_active?"Деактивировать":"Активировать"} доступ ${user.display_name}?`))return;await setAccessUserActive(user.id,!user.is_active);await load();if(user.id===actor?.id)await refresh();}
 return <><Header/><ServiceDeskAdminNav/><PageLayout title="Менеджеры и права"><Card><form className="filter-grid" onSubmit={(e)=>void create(e)}><Input name="identity" label="Identity subject" required/><Input name="email" label="Email" type="email" required/><Input name="name" label="Имя" required/><Input name="department" label="Подразделение"/><Input name="position" label="Должность"/><Select name="type" label="Тип доступа"><option value="manager">Менеджер</option><option value="service_desk_admin">Администратор Service Desk</option></Select><Button>Предоставить доступ</Button></form></Card><Card><Input label="Поиск" value={q} onChange={e=>setQ(e.target.value)}/>{error&&<p className="form-error">{error}</p>}<Table><table><thead><tr><th>Пользователь</th><th>Тип</th><th>Права</th><th>Статус</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{user.display_name}</strong><br/><small>{user.email} · {user.department||"—"} · {user.position||"—"}</small></td><td>{user.access_type==="service_desk_admin"?"Администратор SD":"Менеджер"}</td><td>{user.access_type==="service_desk_admin"?<strong>Все права Service Desk</strong>:<div className="capability-grid">{capabilities.map(cap=><label key={cap}><input type="checkbox" checked={user.capabilities.includes(cap)} onChange={()=>void toggle(user,cap)}/>{labels[cap]}</label>)}</div>}</td><td><Button variant="secondary" onClick={()=>void active(user)}>{user.is_active?"Деактивировать":"Активировать"}</Button></td></tr>)}</tbody></table></Table></Card></PageLayout></>;
}
